# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Start For Testing"
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm i -g @nestjs/cli
      - run: npm install -g typescript
      - run: npm install
      - run: npm run test
      - run: npm run test:e2e
